Did the task  -Rick and Morty-
mate-academy/jv-rick-and-morty pull request #146
Opened 2024-04-16 14:49 UTC by aksoli666

+created API with two methods:
1) get randomly character
2) get character by part of name
+used public API

2024-04-16 20:09 UTC, MAMentorFX requested changes

2024-04-16 20:09 UTC, MAMentorFX commented on src/main/java/mate/academy/rickandmorty/Application.java
> +@ComponentScan("mate.academy.rickandmorty.mapper")
Your spring application is already scanning this package, so this line is redundant
```suggestion
```

2024-04-16 20:09 UTC, MAMentorFX commented on src/main/java/mate/academy/rickandmorty/client/impl/CharacterClientImpl.java
> +                CharacterResponseDto dataDto = objectMapper
```suggestion
                CharacterResponseDto characterDto = objectMapper
```

2024-04-16 20:09 UTC, MAMentorFX commented on src/main/java/mate/academy/rickandmorty/dto/external/InfoResponseDto.java
> +public class InfoResponseDto {
You can use @Data with Dtos instead of these annotations

2024-04-16 20:09 UTC, MAMentorFX commented on src/main/java/mate/academy/rickandmorty/dto/external/InfoResponseDto.java
> +    private String nextUrl;
Have you checked the result? I don't think `next` deserializes into `nextUrl`

2024-04-16 20:09 UTC, MAMentorFX commented on src/main/java/mate/academy/rickandmorty/service/impl/CharacterServiceImpl.java
> +    public InternalCharacterDto getRandomlyCharacter() {
@Transactional. You make more than one call to DB

2024-04-16 20:09 UTC, MAMentorFX commented on src/main/java/mate/academy/rickandmorty/service/impl/CharacterServiceImpl.java
> +                .toList();
Mapstruct supports mapping collections from the box

2024-04-16 20:09 UTC, MAMentorFX commented on src/main/java/mate/academy/rickandmorty/controller/CharacterController.java
> +    @Operation(summary = "Get randomly character", description = "Return a character by random id")
```suggestion
    @Operation(summary = "Get random character", description = "Return a character by random id")
```
Also `Return a character by random id` I don't see any id in method declaration, think of better description, it's confusing

2024-04-16 20:09 UTC, MAMentorFX commented on src/main/java/mate/academy/rickandmorty/controller/CharacterController.java
> +    public InternalCharacterDto getRandomlyCharacter() {
```suggestion
    public InternalCharacterDto getRandomCharacter() {
```

2024-04-16 20:09 UTC, MAMentorFX commented on src/main/java/mate/academy/rickandmorty/controller/CharacterController.java
> +        return characterService.getRandomlyCharacter();
```suggestion
        return characterService.getRandomCharacter();
```

2024-04-16 20:09 UTC, MAMentorFX commented on src/main/java/mate/academy/rickandmorty/controller/CharacterController.java
> +    public List<InternalCharacterDto> getCharacterByName(String name) {
```suggestion
    public List<InternalCharacterDto> getCharactersByName(@RequestParam String name) {
```

2024-04-16 20:09 UTC, MAMentorFX commented on src/main/java/mate/academy/rickandmorty/client/impl/CharacterClientImpl.java
> +    public void getAndSaveCharacters() {
![image](https://github.com/mate-academy/jv-rick-and-morty/assets/164332253/872be4d0-2359-4deb-919f-de7277cba2ab)
![image](https://github.com/mate-academy/jv-rick-and-morty/assets/164332253/e492aa91-aa19-4233-9fde-8fc5be22a8b6)
You need to tell Spring that you want to fetch all the data once, at the start of the application. Now your application never calls this method. So no data is fetched

2024-04-16 20:09 UTC, MAMentorFX commented on src/main/java/mate/academy/rickandmorty/service/impl/CharacterServiceImpl.java
> +        return characterRepository.findAllByName(name)
```suggestion
        return characterRepository.findAllByNameIn(name)
```
![image](https://github.com/mate-academy/jv-rick-and-morty/assets/164332253/64482660-a3b0-486f-a6c3-04f4aff5d53a)
Let's say you have Rick in DB. If I call getCharacterByName("ck"), I want it to return Rick, Now your method will return Rick only if I call getCharacterByName("Rick")

2024-04-16 20:09 UTC, MAMentorFX commented on src/main/java/mate/academy/rickandmorty/service/impl/CharacterServiceImpl.java
> +    public List<InternalCharacterDto> getCharacterByName(String name) {
```suggestion
    public List<InternalCharacterDto> getCharactersByName(String name) {
```

2024-04-18 06:55 UTC, MAMentorFX requested changes

2024-04-18 06:55 UTC, MAMentorFX commented on src/main/java/mate/academy/rickandmorty/repository/CharacterRepository.java
> +    List<Character> findAllByNameContaining(String partialName);
```suggestion
    List<Character> findAllByNameContainingIgnoreCase(String partialName);
```

2024-04-18 06:55 UTC, MAMentorFX commented on src/main/java/mate/academy/rickandmorty/client/impl/CharacterClientImpl.java
> +        HttpClient httpClient = HttpClient.newHttpClient();
renaming to `fetch` doesn't help Spring understand that that it should call this method at the beginning of the application bootstrapping. I hope you are familiar with  bean's lifecycle, there's a method init(), look up what the annotation in Spring helps you put this method in init() method.

2024-04-18 06:55 UTC, MAMentorFX commented on src/main/java/mate/academy/rickandmorty/service/impl/CharacterServiceImpl.java
> +                .collect(Collectors.toList());
`List<InternalCharacterDto> toDtoList(List<Character> characters)`

2024-04-18 06:55 UTC, MAMentorFX commented on src/main/java/mate/academy/rickandmorty/client/impl/CharacterClientImpl.java
> +                .toList();
Mapstruct supports mapping collections from the box

2024-04-18 06:55 UTC, MAMentorFX commented on src/main/java/mate/academy/rickandmorty/client/impl/CharacterClientImpl.java
> +        Iterable<Character> characters = externalCharacterDtoList.stream()
```suggestion
        List<Character> characters = externalCharacterDtoList.stream()
```

2024-04-23 18:29 UTC, okuzan approved these changes

2024-04-23 18:29 UTC, okuzan commented on src/main/java/mate/academy/rickandmorty/service/impl/CharacterServiceImpl.java
> +
```suggestion
                characterRepository.findAllByNameContainingIgnoreCase(partialName));
```

2024-04-23 18:29 UTC, okuzan commented on src/main/java/mate/academy/rickandmorty/Application.java
> +@ComponentScan("mate.academy.rickandmorty.mapper")
not fixed, doesn't it work without it?

2024-06-21 19:37 UTC, closed without merging