develop
mate-academy/jv-rick-and-morty pull request #180
Opened 2024-08-03 13:17 UTC by vladshender

2024-08-06 09:27 UTC, Elena-Bruyako requested changes

2024-08-06 09:27 UTC, Elena-Bruyako commented on src/main/java/mate/academy/rickandmorty/repository/character/spec/NameSpecificationProvider.java
> +        return "name";
name should be constant

2024-08-06 09:27 UTC, Elena-Bruyako commented on src/main/java/mate/academy/rickandmorty/repository/character/CharacterSpecificationBuilder.java
> +            spec = spec.and(specificationProviderManager.getSpecificationProvider("name")
name should be constant

2024-08-06 09:27 UTC, Elena-Bruyako commented on src/main/java/mate/academy/rickandmorty/service/CharacterService.java
> +
```suggestion
```

2024-08-06 09:27 UTC, Elena-Bruyako commented on src/main/java/mate/academy/rickandmorty/service/CharacterServiceImpl.java
> +                () -> new RuntimeException("Can`t find character by id: " + id));
EntityNotFoundException

2024-08-06 09:27 UTC, Elena-Bruyako commented on src/main/java/mate/academy/rickandmorty/service/rickandmortyapi/RickAndMortyClient.java
> +
```suggestion
```

2024-08-06 09:27 UTC, Elena-Bruyako commented on src/main/java/mate/academy/rickandmorty/service/rickandmortyapi/RickAndMortyService.java
> +
```suggestion
```

2024-08-06 09:27 UTC, Elena-Bruyako commented on src/main/java/mate/academy/rickandmorty/service/rickandmortyapi/RickAndMortyService.java
> +    private static final String BASE_URL = "https://rickandmortyapi.com/api/character/?page=%s";
You can use `@Value` and get url from properties

2024-08-08 13:32 UTC, okuzan requested changes

2024-08-08 13:32 UTC, okuzan commented on src/main/java/mate/academy/rickandmorty/repository/character/spec/NameSpecificationProvider.java
> +    public static final String WILDCARD = "%";
```suggestion
    private static final String NAME_KEY = "name";
    private static final String WILDCARD = "%";
```

2024-08-08 13:32 UTC, okuzan commented on src/main/java/mate/academy/rickandmorty/repository/character/CharacterSpecificationProviderManager.java
> +                .orElseThrow(() -> new RuntimeException("Can`t find correct specification for key: "
```suggestion
                .filter(provider -> provider.getKey().equals(key))
                .findFirst()
                .orElseThrow(() -> new NoSuchElementException("Can`t find correct specification for key: "
```

2024-08-08 13:32 UTC, okuzan commented on src/main/java/mate/academy/rickandmorty/model/Character.java
> +
```suggestion
```

2024-08-08 13:32 UTC, okuzan commented on src/main/java/mate/academy/rickandmorty/dto/CharacterResultsDataDto.java
> +
```suggestion
    private String name;
    private String status;
```

2024-08-08 13:32 UTC, okuzan commented on src/main/java/mate/academy/rickandmorty/controller/CharactersController.java
> +@RequestMapping("/character")
```suggestion
@RequestMapping("/characters")
```

2024-08-08 13:32 UTC, okuzan commented on src/main/java/mate/academy/rickandmorty/controller/CharactersController.java
> +    @GetMapping("/search")
```suggestion
```
More RESTful without it, URLs usually don't contain verbs, we have HTTP verb to imply action

2024-08-08 13:32 UTC, okuzan commented on src/main/java/mate/academy/rickandmorty/dto/CharacterResultsDataDto.java
> +@Setter
It's ok to use @Data for all dtos, let's make it consistent

2024-08-08 13:32 UTC, okuzan commented on src/main/java/mate/academy/rickandmorty/service/rickandmortyapi/RickAndMortyService.java
> +        }
try to rewrite condition to not use while true, generally a bad practice

2024-08-10 12:56 UTC, sarakhmen approved these changes

2026-03-08 07:19 UTC, closed without merging