Jv rick and morty impl
mate-academy/jv-rick-and-morty pull request #194
Opened 2024-09-25 16:35 UTC by mkazarian-1

2024-09-25 19:07 UTC, ahoienko requested changes
Nice, but significant improvements is required

2024-09-25 19:07 UTC, ahoienko commented on src/main/java/mate/academy/rickandmorty/Application.java
> +    private static final String RICK_AND_MORTY_API_CHARACTER_URL = "https://rickandmortyapi.com/api/character";
This parameter should be configurable (in application properties), not hardcoded

2024-09-25 19:07 UTC, ahoienko commented on target/classes/application.properties
> +spring.datasource.password=henghfdf
Don`t push credentials to github

2024-09-25 19:07 UTC, ahoienko commented on target/classes/application.properties
> +spring.jpa.open-in-view=false
missing empty line

2024-09-25 19:07 UTC, ahoienko commented on target/maven-status/maven-compiler-plugin/compile/default-compile/inputFiles.lst
> +E:\Java_projects\jv-rick-and-morty\src\main\java\mate\academy\rickandmorty\controler\CharacterController.java
Are you sure that this file should be on git?

2024-09-25 19:07 UTC, ahoienko commented on target/maven-status/maven-compiler-plugin/compile/default-compile/createdFiles.lst
> +mate\academy\rickandmorty\external\api\service\ExternalCharacterService.class
Are you sure that this file should be on git?

2024-09-25 19:07 UTC, ahoienko commented on target/checkstyle-result.xml
> +<error line="43" column="51" severity="error" message="&apos;)&apos; is preceded with whitespace." source="com.puppycrawl.tools.checkstyle.checks.whitespace.ParenPadCheck"/>
Are you sure that this file should be on git?

2024-09-25 19:07 UTC, ahoienko commented on target/checkstyle-cachefile
> +E\:\\Java_projects\\jv-rick-and-morty\\src\\main\\java\\mate\\academy\\rickandmorty\\external\\api\\service\\GetClient.java=1727282829687
Are you sure that this file should be on git?

2024-09-25 19:07 UTC, ahoienko commented on target/checkstyle-cachefile
> +#Wed Sep 25 19:54:02 EEST 2024
target should be in git ignore

2024-09-25 19:07 UTC, ahoienko commented on src/main/resources/application.properties
> +spring.datasource.password=henghfdf
Don`t push credentials on git

2024-09-25 19:07 UTC, ahoienko commented on src/main/resources/application.properties
> +spring.jpa.open-in-view=false
add empty line

2024-09-25 19:07 UTC, ahoienko commented on src/main/java/mate/academy/rickandmorty/dto/external/CharacterResponseDto.java
> +}
Why some dto`s is records and other are not? I suggest you to choose approach and use records or common classes

2024-09-25 19:07 UTC, ahoienko commented on src/main/java/mate/academy/rickandmorty/external/api/service/impl/GetCharactersClientImpl.java
> +            throw new RuntimeException("Can't get response from: " + url, e);
Please create and throw custom exception

2024-09-25 19:07 UTC, ahoienko commented on src/main/java/mate/academy/rickandmorty/external/api/service/impl/GetCharactersClientImpl.java
> +            throw new RuntimeException(
Please create and throw custom exception, or you can remove try catch and handle JsonProcessingException  in global exception handler. But I think that this exception is already handled by spring

2024-09-25 19:07 UTC, ahoienko commented on src/main/java/mate/academy/rickandmorty/external/api/service/GetClient.java
> +public interface GetClient<T> {
```suggestion
public interface CharacterClient {
//I don`t see reason to make parametrization here
```

2024-09-25 19:07 UTC, ahoienko commented on src/main/java/mate/academy/rickandmorty/external/api/service/GetClient.java
> +    T getDtoFromApi(String url);
```suggestion
    dto.... getDtoFromApi(String url);
```

2024-09-25 19:07 UTC, ahoienko commented on src/main/java/mate/academy/rickandmorty/Application.java
> +    private static final String RICK_AND_MORTY_API_CHARACTER_URL = "https://rickandmortyapi.com/api/character";
Also this url can be moved to client class

2024-09-25 19:07 UTC, ahoienko commented on src/main/java/mate/academy/rickandmorty/external/api/service/impl/DbSynchronizationServiceImpl.java
> +            fullResponseDto.getResults().forEach(externalCharacterService::saveOrUpdate);
In current implementation you will make N requests to DB to save N characters

2024-09-25 19:07 UTC, ahoienko commented on src/main/java/mate/academy/rickandmorty/repository/CharacterRepository.java
> +    List<Character> findByExternalId(String externalId);
Why this returns list?

2024-09-25 19:07 UTC, ahoienko commented on src/main/java/mate/academy/rickandmorty/external/api/service/impl/ExternalCharacterServiceImpl.java
> +            characterMapper.updateCharacterFromResponseDto(characterResponseDto, character);
```suggestion
            Character updatedCharacter = characterMapper.toCharacter(characterResponseDto);
            updatedCharacter.setId(existingCharacter.getId)
            
```

2024-09-27 07:43 UTC, mkazarian-1 commented on target/classes/application.properties
> +spring.jpa.open-in-view=false
May you explain me why is it matter?

2024-09-28 07:25 UTC, Elena-Bruyako approved these changes

2025-05-09 13:13 UTC, closed without merging