Implemented task
mate-academy/jv-rick-and-morty pull request #49
Opened 2023-11-07 00:02 UTC by OlegMR0

2023-11-07 16:16 UTC, olekskov requested changes

2023-11-07 16:16 UTC, olekskov commented on src/main/java/mate/academy/rickandmorty/controller/CharacterController.java
> +@RequestMapping("/api")
i'd expand path in order to be able to add other endpoints later
```suggestion
@RequestMapping("/api/characters")

```

2023-11-07 16:16 UTC, olekskov commented on src/main/java/mate/academy/rickandmorty/repository/CharacterRepository.java
> +    Optional<Character> findById(Long id);
these methods are present by default in JpaRepository, no need to duplicate
```suggestion
```

2023-11-07 16:16 UTC, olekskov commented on src/main/java/mate/academy/rickandmorty/service/CharacterServiceImpl.java
> +    }
Please move method to CharacterClientImpl
This service mainly works to process our users' requests and initialization is logically out of this scope
```suggestion
```

2023-11-07 16:16 UTC, olekskov commented on src/main/java/mate/academy/rickandmorty/service/CharacterServiceImpl.java
> +        return repository.save(character);
Cannot understand why we reset id and call save for character we just retrieved from DB

2023-11-07 16:16 UTC, olekskov commented on src/main/java/mate/academy/rickandmorty/service/CharacterServiceImpl.java
> +    public Character saveRandomCharacter() {
you should unify if you service returns DTOs or models

2023-11-07 16:16 UTC, olekskov commented on src/main/java/mate/academy/rickandmorty/controller/CharacterController.java
> +    public Character saveRandomCharacter() {
please use dtos and hide internal implementation of classes

2023-11-08 12:30 UTC, Rommelua approved these changes

2023-11-08 12:30 UTC, Rommelua commented on src/main/java/mate/academy/rickandmorty/controller/CharacterController.java
> +        return characterService.getAll();
Have you ever heard about YAGNI?
![image](https://github.com/mate-academy/jv-rick-and-morty/assets/20326858/121794dd-0991-490a-9b56-234f94401a2a)

2023-12-13 08:13 UTC, closed without merging