implemented task
mate-academy/jv-rick-and-morty pull request #82
Opened 2023-12-22 17:59 UTC by DenysMaksymKachalup

2023-12-22 18:21 UTC, sokimaaa requested changes

2023-12-22 18:21 UTC, sokimaaa commented on pom.xml
> +		</dependency>
dont need this
```suggestion
```

2023-12-22 18:21 UTC, sokimaaa commented on src/main/java/mate/academy/rickandmorty/controller/CharacterController.java
> +@RequestMapping(value = "/character")
recall URI REST Naming convention and fix all issues

2023-12-22 18:21 UTC, sokimaaa commented on src/main/java/mate/academy/rickandmorty/repository/CharacterRepository.java
> +@Repository
dont need this
```suggestion
```

2023-12-22 18:21 UTC, sokimaaa commented on src/main/java/mate/academy/rickandmorty/service/impl/CharacterClientImpl.java
> +    private final HttpClient httpClient = HttpClient.newHttpClient();
You have Spring IoC to avoid instantiation like this.
```suggestion
    private final HttpClient httpClient = HttpClient.newHttpClient();
```

2023-12-22 18:21 UTC, sokimaaa commented on src/main/java/mate/academy/rickandmorty/service/impl/CharacterClientImpl.java
> +        String apiUrl = BASE_URL;
Use constant directly where need
```suggestion
```

2023-12-22 18:21 UTC, sokimaaa commented on src/main/java/mate/academy/rickandmorty/service/impl/CharacterClientImpl.java
> +        } while (apiUrl != null);
```suggestion
            CharacterResponseDataDto characterResponseDataDto = getCharacters(apiUrl);
            characters.addAll(characterResponseDataDto.results());
            apiUrl = characterResponseDataDto.info().next();
```

2023-12-22 18:21 UTC, sokimaaa commented on src/main/java/mate/academy/rickandmorty/service/impl/CharacterServiceImpl.java
> +    private final Random random = new Random();
You have spring IoC to avoid instantiation like this
```suggestion
    private final Random random = new Random();
```

2023-12-22 18:21 UTC, sokimaaa commented on src/main/java/mate/academy/rickandmorty/service/impl/CharacterServiceImpl.java
> +    }
Dont use @PostConstruct for business rules and\or instantiation of the whole application logic

2023-12-22 18:21 UTC, sokimaaa commented on src/main/java/mate/academy/rickandmorty/service/impl/CharacterServiceImpl.java
> +                .orElseThrow(RuntimeException::new);
Confusing error, consider using custom exception or at least give self-descriptive reason of error
```suggestion
                .orElseThrow(RuntimeException::new);
```

2023-12-22 18:56 UTC, sokimaaa requested changes

2023-12-22 18:56 UTC, sokimaaa commented on src/main/java/mate/academy/rickandmorty/service/impl/CharacterClientImpl.java
> +        HttpClient httpClient = HttpClient.newHttpClient();
Dont need to instantiate httpClient each time method is invoked
```suggestion
```

2023-12-22 18:56 UTC, sokimaaa commented on src/main/java/mate/academy/rickandmorty/controller/CharacterController.java
> +    }
This method should be invoked once, 
no need to leave someone's ability to fill our database with duplicates. 
```suggestion
```

2023-12-24 18:28 UTC, Sanderfuck approved these changes

2026-03-29 16:05 UTC, closed without merging